### ISSUE TITLE
i get HID <= 6982 fail to loading

### ISSUE THREAD

**Issue by jasonbhwong** [LedgerHQ/nanos-nonsecure-firmware-releases#1]
i use the ledger nano s, system ubuntu 18.04.
i use mcu_1.6_over_0.8.hex(this file come from https://media.readthedocs.org/pdf/ledger/latest/ledger.pdf ) to loading, it's ok.
but use these file is fail to loading,what happen?

////////////////////////////////////////////error msg///////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jason/nanos-nonsecure-firmware-1.1/build/stm32f042_nanos_seproxyhal/ledgerblue/loadMCU.py", line 58, in <module>
    loader.run(args.bootAddr)
  File "ledgerblue/hexLoader.py", line 514, in run
    self.boot(bootoffset, signature)
  File "ledgerblue/hexLoader.py", line 326, in boot
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "ledgerblue/hexLoader.py", line 202, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "ledgerblue/comm.py", line 133, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6982 (Have you uninstalled the existing CA with resetCustomCA first?)

**Comment by danuker** [comment]
I have not tried this; but the software seems to be complaining about a custom CA (certificate authority) that you added (perhaps to recognize your own firmware certificate).

Apparently, you need to call "resetCustomCA" to remove the CA.

You can find how to do that in the PDF you linked (by searching for resetCustomCA).
